export const LOGIN_PROGRESS = 'LOGIN_PROGRESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const FORGOTPASSWORD_PROGRESS = 'FORGOTPASSWORD_PROGRESS';
export const FORGOTPASSWORD_SUCCESS = 'FORGOTPASSWORD_SUCCESS';
export const FORGOTPASSWORD_FAIL = 'FORGOTPASSWORD_FAIL';

export const RESETPASSWORD_PROGRESS = 'RESETPASSWORD_PROGRESS';
export const RESETPASSWORD_SUCCESS = 'RESETPASSWORD_SUCCESS';
export const RESETPASSWORD_FAIL = 'RESETPASSWORD_FAIL';

export const GETPROJECTTARGET_PROGRESS = 'GETPROJECTTARGET_PROGRESS';
export const GETPROJECTTARGET_SUCCESS = 'GETPROJECTTARGET_SUCESS';
export const GETPROJECTTARGET_FAIL = 'GETPROJECTTARGET_FAIL';

export const FETCH_VENDER_REQUEST = 'FETCH_VENDER_REQUEST';
export const FETCH_VENDER_SUCCESS = 'FETCH_VENDER_SUCCESS';
export const FETCH_VENDER_FAILURE = 'FETCH_VENDER_FAILURE';

export const EDITPROJECTTARGET_PROGRESS = 'EDITPROJECTTARGET_PROGRESS';
export const EDITPROJECTTARGET_SUCCESS = 'EDITPROJECTTARGET_SUCCESS';
export const EDITPROJECTTARGET_FAIL = 'EDITPROJECTTARGET_FAIL';

export const GETRESOURCE_PROGRESS = 'GETRESOURCE_PROGRESS';
export const GETRESOURCE_SUCCESS = 'GETRESOURCE_SUCCESS';
export const GETRESOURCE_FAIL = 'GETRESOURCE_FAIL';

export const ADDPROJECT_PROGRESS = 'ADDPROJECT_PROGRESS';
export const ADDPROJECT_SUCCESS = 'ADDPROJECT_SUCCESS';
export const ADDPROJECT_FAIL = 'ADDPROJECT_FAIL';

export const DELETEPROJECT_PROGRESS = 'DELETEPROJECT_PROGRESS';
export const DELETEPROJECT_SUCCESS = 'DELETEPROJECT_SUCCESS';
export const DELETEPROJECT_FAIL = 'DELETEPROJECT_FAIL';

export const EDITVENDOR_PROGRESS = 'EDITVENDOR_PROGRESS';
export const EDITVENDOR_SUCCESS = 'EDITVENDOR_SUCCESS';
export const EDITVENDOR_FAIL = 'EDITVENDOR_FAIL';

export const ADDVENDOR_PROGRESS = 'ADDVENDOR_PROGRESS';
export const ADDVENDOR_SUCCESS = 'ADDVENDOR_SUCCESS';
export const ADDVENDOR_FAIL = 'ADDVENDOR_FAIL';

export const DELETEVENDOR_PROGRESS = 'DELETEVENDOR_PROGRESS';
export const DELETEVENDOR_SUCCESS = 'DELETEVENDOR_SUCCESS';
export const DELETEVENDOR_FAIL = 'DELETEVENDOR_FAIl';
export const FETCH_RESOURCE_REQUEST = 'FETCH_RESOURCE_REQUEST';
export const FETCH_RESOURCE_SUCCESS = 'FETCH_RESOURCE_SUCCESS';
export const FETCH_RESOURCE_FAILURE = 'FETCH_RESOURCE_FAILURE';

export const ADD_RESOURCE_REQUEST = 'ADD_RESOURCE_REQUEST';
export const ADD_RESOURCE_SUCCESS = 'ADD_RESOURCE_SUCCESS';
export const ADD_RESOURCE_FAILURE = 'ADD_RESOURCE_FAILURE';

export const DELETE_RESOURCE_REQUEST = 'DELETE_RESOURCE_REQUEST';
export const DELETE_RESOURCE_SUCCESS = 'DELETE_RESOURCE_SUCCESS';
export const DELETE_RESOURCE_FAILURE = 'DELETE_RESOURCE_FAILURE';

export const FETCH_TECHNOLOGY_REQUEST = 'FETCH_TECHNOLOGY_REQUEST';
export const FETCH_TECHNOLOGY_SUCCESS = 'FETCH_TECHNOLOGY_SUCCESS';
export const FETCH_TECHNOLOGY_FAILURE = 'FETCH_TECHNOLOGY_FAILURE';

export const FETCH_ARCHIVED_PROGRESS = 'FETCH_ARCHIVED_PROGRESS';
export const FETCH_ARCHIVED_SUCCESS = 'FETCH_ARCHIVED_SUCCESS';
export const FETCH_ARCHIVED_FAIL = 'FETCH_ARCHIVED_FAIL';

export const ARCHIVEUSER_PROGRESS = 'ARCHIVEUSER_PROGRESS';
export const ARCHIVEUSER_SUCCESS = 'ARCHIVEUSER_SUCCESS';
export const ARCHIVEUSER_FAIL = 'ARCHIVEUSER_FAIL';

export const FETCHINACTIVE_PROGRESS = 'FETCHINACTIVE_PROGRESS';
export const FETCHINACTIVE_SUCCESS = 'FETCHINACTIVE_SUCCESS';
export const FETCHINACTIVE_FAIL = 'FETCHINACTIVE_FAIL';

export const ACTIVERESOURCE_PROGRESS = 'ACTIVERESOURCE_PROGRESS';
export const ACTIVERESOURCE_SUCCESS = 'ACTIVERESOURCE_SUCCESS';
export const ACTIVERESOURCE_FAIL = 'ACTIVERESOURCE_FAIL';

export const DELETERESOURCE_PROGRESS = 'DELETERESOURCE_PROGRESS';
export const DELETERESOURCE_SUCCESS = 'DELETERESOURCE_SUCCESS';
export const DELETERESOURCE_FAIL = 'DELETERESOURCE_FAIL';

export const FETCHEXTERNALPROD_PROGRESS = 'FETCHEXTERNALPROD_PROGRESS';
export const FETCHEXTERNALPROD_SUCCESS = 'FETCHEXTERNALPROD_SUCCESS';
export const FETCHEXTERNALPROD_FAIL = 'FETCHEXTERNALPROD_FAIL';

export const DELETEPRODUCT_PROGRESS = 'DELETEPRODUCT_PROGRESS';
export const DELETEPRODUCT_SUCCESS = 'DELETEPRODUCT_SUCCESS';
export const DELETEPRODUCT_FAIL = 'DELETEPRODUCT_FAIL';

export const ADDPRODUCT_PROGRESS = 'ADDPRODUCT_PROGRESS';
export const ADDPRODUCT_SUCCESS = 'ADDPRODUCT_SUCCESS';
export const ADDPRODUCT_FAIL = 'ADDPRODUCT_FAIL';

export const UPDATEPRODUCT_PROGRESS = 'UPDATEPRODUCT_PROGRESS';
export const UPDATEPRODUCT_SUCCESS = 'UPDATEPRODUCT_SUCCESS';
export const UPDATEPRODUCT_FAIL = 'UPDATEPRODUCT_FAIL';

export const FETCHTECHNOLOFY_PROGRESS = 'FETCHTECHNOLOFY_PROGRESS';
export const FETCHTECHNOLOFY_SUCCESS = 'FETCHTECHNOLOFY_SUCCESS';
export const FETCHTECHNOLOFY_FAIL = 'FETCHTECHNOLOFY_FAIL';

export const ADDTECHNOLGY_PROGRESS = 'ADDTECHNOLGY_PROGRESS';
export const ADDTECHNOLGY_SUCCESS = 'ADDTECHNOLGY_SUCCESS';
export const ADDTECHNOLGY_FAIL = 'ADDTECHNOLGY_FAIL';

export const UPDATETECHNOLOGY_PROGRESS = 'UPDATETECHNOLOGY_PROGRESS';
export const UPDATETECHNOLOGY_SUCCESS = 'UPDATETECHNOLOGY_SUCCESS';
export const UPDATETECHNOLOGY_FAIL = 'UPDATETECHNOLOGY_FAIL';

export const DELETETECHNOLOGY_PROGRESS = 'DELETETECHNOLOGY_PROGRESS';
export const DELETETECHNOLOGY_SUCCESS = 'DELETETECHNOLOGY_SUCCESS';
export const DELETETECHNOLOGY_FAIL = 'DELETETECHNOLOGY_FAIL';

export const FETCHREASON_PROGRESS = 'FETCHREASON_PROGRESS';
export const FETCHREASON_SUCCESS = 'FETCHREASON_SUCCESS';
export const FETCHREASON_FAIL = 'FETCHREASON_FAIL';

export const ADDREASON_PROGRESS = 'ADDREASON_PROGRESS';
export const ADDREASON_SUCCESS = 'ADDREASON_SUCCESS';
export const ADDREASON_FAIL = 'ADDREASON_PROGRESS';

export const EDITREASON_PROGRESS = 'EDITREASON_PROGRESS';
export const EDITREASON_SUCCESS = 'EDITREASON_SUCCESS';
export const EDITREASON_FAIL = 'EDITREASON_FAIL';

export const DELETEREASON_PROGRESS = 'DELETEREASON_PROGRESS';
export const DELETEREASON_SUCCESS = 'DELETEREASON_SUCCESS';
export const DELETEREASON_FAIL = 'DELETEREASON_FAIL';

export const FETCHACCOUNT_PROGRESS = 'FETCHACCOUNT_PROGRESS';
export const FETCHACCOUNT_SUCCESS = 'FETCHACCOUNT_SUCCESS';
export const FETCHACCOUNT_FAIL = 'FETCHACCOUNT_FAIL';

export const ADDACCOUNT_PROGRESS = 'ADDACCOUNT_PROGRESS';
export const ADDACCOUNT_SUCCESS = 'ADDACCOUNT_SUCCESS';
export const ADDACCOUNT_FAIL = 'ADDACCOUNT_PROGRESS';

export const EDITACCOUNT_PROGRESS = 'EDITACCOUNT_PROGRESS';
export const EDITACCOUNT_SUCCESS = 'EDITACCOUNT_SUCCESS';
export const EDITACCOUNT_FAIL = 'EDITACCOUNT_FAIL';

export const DELETEACCOUNT_PROGRESS = 'DELETEACCOUNT_PROGRESS';
export const DELETEACCOUNT_SUCCESS = 'DELETEACCOUNT_SUCCESS';
export const DELETEACCOUNT_FAIL = 'DELETEACCOUNT_FAIL';


